### ISSUE TITLE
Associations and indentation

### ISSUE THREAD

**Issue by jmriddell** [Breeder/ReaSyntax#3]
Syntax highlighting are good. Just had to add the jsfx and jsfx-inc associations and fix the indentation that is of 2 spaces inside reaper, just wanted to keep the same format.

**Comment by X-Raym** [comment]
Do you have any pull request to propose for the jsfx association ? Did you modified ReaSyntax code for that ?

**Comment by jmriddell** [comment]
Now I have a pull request for the indentation. Just changed the language specific settings in sublime text.

**Comment by X-Raym** [comment]
Merged : https://github.com/Breeder/ReaSyntax/pull/4
