### ISSUE TITLE
new completions are stealing from "then"

### ISSUE THREAD

**Issue by benjohnson2001** [Breeder/ReaSyntax#6]
![tabIsNotForYou](https://user-images.githubusercontent.com/3026885/115359076-4f212e00-a18c-11eb-9f7b-b758d7635dbd.png)

this thing keeps autocompleting off tab/enter all of a sudden and its driving me crazy

**Comment by Breeder** [comment]
That's issue with Sublime Text, nothing I can do about it.  I tried it now and you only get a list of recommendations, if you press space after writing then, it disappears. You can also edit completion files by yourself and remove the offending completions. Closing the issue.

**Comment by Breeder** [comment]
That's the issue with the Sublime Text, nothing I can do about it except removing completions (maybe we can hook into Sublime Text API and fix this, but meh...I don't have the time to learn that now). You can also edit completion files by yourself and remove the offending completions. I will be removing these 3 comletions from the next build in a few hours or so.

Closing the issue and thank you for the report.
